In [1]:
import pandas as pd

df = pd.read_parquet("datamart/gold/label_store/gold_label_store_2023_07_01.parquet")
df.head(5)

                 loan_id Customer_ID  label   label_def snapshot_date
0  CUS_0x1037_2023_01_01  CUS_0x1037      0  30dpd_6mob    2023-07-01
1  CUS_0x1069_2023_01_01  CUS_0x1069      0  30dpd_6mob    2023-07-01
2  CUS_0x114a_2023_01_01  CUS_0x114a      0  30dpd_6mob    2023-07-01
3  CUS_0x1184_2023_01_01  CUS_0x1184      0  30dpd_6mob    2023-07-01
4  CUS_0x1297_2023_01_01  CUS_0x1297      1  30dpd_6mob    2023-07-01

In [3]:
df = pd.read_parquet("datamart/silver/loan_daily/silver_loan_daily_2023_07_01.parquet")
df.head(20)

,loan_id,Customer_ID,loan_start_date,tenure,installment_num,loan_amt,due_amt,paid_amt,overdue_amt,balance,snapshot_date,mob,installments_missed,first_missed_date,dpd
0,CUS_0x1000_2023_05_01,CUS_0x1000,2023-05-01,10,2,10000.0,1000.0,1000.0,0.0,8000.0,2023-07-01,2,0,None,0
1,CUS_0x1037_2023_01_01,CUS_0x1037,2023-01-01,10,6,10000.0,1000.0,1000.0,0.0,4000.0,2023-07-01,6,0,None,0
2,CUS_0x1044_2023_06_01,CUS_0x1044,2023-06-01,10,1,10000.0,1000.0,1000.0,0.0,9000.0,2023-07-01,1,0,None,0
3,CUS_0x104e_2023_06_01,CUS_0x104e,2023-06-01,10,1,10000.0,1000.0,1000.0,0.0,9000.0,2023-07-01,1,0,None,0
4,CUS_0x1056_2023_04_01,CUS_0x1056,2023-04-01,10,3,10000.0,1000.0,3000.0,0.0,7000.0,2023-07-01,3,0,None,0
5,CUS_0x105c_2023_06_01,CUS_0x105c,2023-06-01,10,1,10000.0,1000.0,1000.0,0.0,9000.0,2023-07-01,1,0,None,0
6,CUS_0x1069_2023_01_01,CUS_0x1069,2023-01-01,10,6,10000.0,1000.0,1000.0,0.0,4000.0,2023-07-01,6,0,None,0
7,CUS_0x108a_2023_05_01,CUS_0x108a,2023-05-01,10,2,10000.0,1000.0,1000.0,0.0,8000.0,2023-07-01,2,0,None,0
8,CUS_0x10aa_2023_02_01,CUS_0x10aa,2023-02-01,10,5,10000.0,1000.0,1000.0,0.0,5000.0,2023-07-01,5,0,None,0
9,CUS_0x10bb_2023_03_01,CUS_0x10bb,2023-03-01,10,4,10000.0,1000.0,1000.0,0.0,6000.0,2023-07-01,4,0,None,0
10,CUS_0x10eb_2023_03_01,CUS_0x10eb,2023-03-01,10,4,10000.0,1000.0,1000.0,0.0,6000.0,2023-07-01,4,0,None,0
11,CUS_0x10ee_2023_06_01,CUS_0x10ee,2023-06-01,10,1,10000.0,1000.0,1000.0,0.0,9000.0,2023-07-01,1,0,None,0
12,CUS_0x10f9_2023_05_01,CUS_0x10f9,2023-05-01,10,2,10000.0,1000.0,1000.0,0.0,8000.0,2023-07-01,2,0,None,0
13,CUS_0x1119_2023_05_01,CUS_0x1119,2023-05-01,10,2,10000.0,1000.0,0.0,1000.0,9000.0,2023-07-01,2,1,2023-06-01,30
14,CUS_0x1130_2023_07_01,CUS_0x1130,2023-07-01,10,0,10000.0,0.0,0.0,0.0,10000.0,2023-07-01,0,0,None,0
15,CUS_0x1132_2023_03_01,CUS_0x1132,2023-03-01,10,4,10000.0,1000.0,0.0,2000.0,8000.0,2023-07-01,4,2,2023-05-01,61
16,CUS_0x1135_2023_03_01,CUS_0x1135,2023-03-01,10,4,10000.0,1000.0,1000.0,0.0,6000.0,2023-07-01,4,0,None,0
17,CUS_0x1136_2023_06_01,CUS_0x1136,2023-06-01,10,1,10000.0,1000.0,1000.0,0.0,9000.0,2023-07-01,1,0,None,0
18,CUS_0x113e_2023_02_01,CUS_0x113e,2023-02-01,10,5,10000.0,1000.0,0.0,2000.0,7000.0,2023-07-01,5,2,2023-05-01,61
19,CUS_0x1140_2023_02_01,CUS_0x1140,2023-02-01,10,5,10000.0,1000.0,1000.0,0.0,5000.0,2023-07-01,5,0,None,0

In [4]:
df = pd.read_csv("datamart/bronze/lms/bronze_loan_daily_2023_07_01.csv")
df.head(20)

,loan_id,Customer_ID,loan_start_date,tenure,installment_num,loan_amt,due_amt,paid_amt,overdue_amt,balance,snapshot_date
0,CUS_0x1000_2023_05_01,CUS_0x1000,2023-05-01,10,2,10000,1000.0,1000.0,0.0,8000.0,2023-07-01
1,CUS_0x1037_2023_01_01,CUS_0x1037,2023-01-01,10,6,10000,1000.0,1000.0,0.0,4000.0,2023-07-01
2,CUS_0x1044_2023_06_01,CUS_0x1044,2023-06-01,10,1,10000,1000.0,1000.0,0.0,9000.0,2023-07-01
3,CUS_0x104e_2023_06_01,CUS_0x104e,2023-06-01,10,1,10000,1000.0,1000.0,0.0,9000.0,2023-07-01
4,CUS_0x1056_2023_04_01,CUS_0x1056,2023-04-01,10,3,10000,1000.0,3000.0,0.0,7000.0,2023-07-01
5,CUS_0x105c_2023_06_01,CUS_0x105c,2023-06-01,10,1,10000,1000.0,1000.0,0.0,9000.0,2023-07-01
6,CUS_0x1069_2023_01_01,CUS_0x1069,2023-01-01,10,6,10000,1000.0,1000.0,0.0,4000.0,2023-07-01
7,CUS_0x108a_2023_05_01,CUS_0x108a,2023-05-01,10,2,10000,1000.0,1000.0,0.0,8000.0,2023-07-01
8,CUS_0x10aa_2023_02_01,CUS_0x10aa,2023-02-01,10,5,10000,1000.0,1000.0,0.0,5000.0,2023-07-01
9,CUS_0x10bb_2023_03_01,CUS_0x10bb,2023-03-01,10,4,10000,1000.0,1000.0,0.0,6000.0,2023-07-01
10,CUS_0x10eb_2023_03_01,CUS_0x10eb,2023-03-01,10,4,10000,1000.0,1000.0,0.0,6000.0,2023-07-01
11,CUS_0x10ee_2023_06_01,CUS_0x10ee,2023-06-01,10,1,10000,1000.0,1000.0,0.0,9000.0,2023-07-01
12,CUS_0x10f9_2023_05_01,CUS_0x10f9,2023-05-01,10,2,10000,1000.0,1000.0,0.0,8000.0,2023-07-01
13,CUS_0x1119_2023_05_01,CUS_0x1119,2023-05-01,10,2,10000,1000.0,0.0,1000.0,9000.0,2023-07-01
14,CUS_0x1130_2023_07_01,CUS_0x1130,2023-07-01,10,0,10000,0.0,0.0,0.0,10000.0,2023-07-01
15,CUS_0x1132_2023_03_01,CUS_0x1132,2023-03-01,10,4,10000,1000.0,0.0,2000.0,8000.0,2023-07-01
16,CUS_0x1135_2023_03_01,CUS_0x1135,2023-03-01,10,4,10000,1000.0,1000.0,0.0,6000.0,2023-07-01
17,CUS_0x1136_2023_06_01,CUS_0x1136,2023-06-01,10,1,10000,1000.0,1000.0,0.0,9000.0,2023-07-01
18,CUS_0x113e_2023_02_01,CUS_0x113e,2023-02-01,10,5,10000,1000.0,0.0,2000.0,7000.0,2023-07-01
19,CUS_0x1140_2023_02_01,CUS_0x1140,2023-02-01,10,5,10000,1000.0,1000.0,0.0,5000.0,2023-07-01